### Get all blogs
GET http://localhost:3003/api/blogs

### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Full Stack Open osa 4",
  "author": "Teo",
  "url": "https://fullstackopen.com",
  "likes": 10
}
